before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

stages:
  - deploy-to-test

deploy-to-test:
  only:
    - master
  stage: deploy-to-test
  script:
    - bash runner-script.sh # shell script that will run on "deploy" runner
  tags:
    - deploy # run on a specific runner